Review
Seplaz/karty-podskazhut pull request #1
Opened 2024-01-29 16:27 UTC by Seplaz

2024-01-29 17:16 UTC, Savallera requested changes
## Здравствуйте! У Вас отличная работа, что отметила

### Положительные моменты:

* Все комментарии в коде с пометкой **Отлично**.
* Файловая структура проекта единообразна и логична
* Валидный HTML и CSS
* Нет ошибок в консоли
* Аккуратное форматирование кода
* Для организации лейаута ключевых блоков использован flex или grid
* Переключение цветовых схем реализовано корректно
* Корректно реализована адаптивная верстка


### Что требует доработки:

* Все комментарии в коде с пометкой **Надо исправить**

### Что можно сделать лучше:

* Все комментарии в коде с пометкой **Можно лучше**
* Хорошо бы добавить между предлогом и словом неразрывные пробелы, чтобы не было повисших предлогов. https://www.artlebedev.ru/typograf/
* [Как создать липкий футер с помощью flexbox](https://webformyself.com/kak-sozdat-lipkij-futer-s-pomoshhyu-flexbox/)

---

    Вносите правки без спешки, следите за тем, что изменилось после внесения той или иной правки в элементе. Убедитесь перед отправкой, что все правки внесены, основные требования соответствуют брифу и чек листу. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут.


---

    Комментарии **Надо исправить** обязательны для исправления.
    Комментарии **Можно лучше** носят рекомендательный характер, их выполнение остается на ваше усмотрение. 


**У Вас все получится! Удачного дня!**

2024-01-29 17:16 UTC, Savallera commented on styles/style.css
> +.theme_dark .content__text-block_type_first-lettered :first-child::first-letter {
Здесь также следует скорректировать селектор

2024-01-29 17:16 UTC, Savallera commented on styles/style.css
> +  padding-inline-start: 4px;
**Надо исправить** Также используйте отступы по старой записи с указанием лево/право, т.к. внутренние не срабатывают пока еще, поддержка в псевдоэлементах такого уровня не полная.

2024-01-30 14:38 UTC, Seplaz commented
Правки внесены

2024-01-31 14:46 UTC, merged